### ISSUE TITLE
The problem of rtems port to openrisc.

### ISSUE THREAD

**Issue by dreamflyforever** [heshamelmatary/rtems-gsoc2014#1]
I have seen your blog, it's so good, and I learn more knoledge from your blog. I just discovered rtems a few days ago, I arm according to your blog(http://heshamelmatary.blogspot.com/2014/06/howto-build-and-run-rtems-on-or1ksim.html) do ti step by step, but no found configure file under the root-direction, do I miss something?

**Comment by heshamelmatary** [comment]
Thanks for your interest in the port. Which step are you stuck in? Which configure script didn't you find? FYI, you can use RTEMS tools [1] for this port (instead of this repo) as all the code in here is upstream. 

[1] https://github.com/RTEMS/

**Comment by dreamflyforever** [comment]
Thanks for your reply. Let me try to solve the problem myself.
